### ISSUE TITLE
Bullets appearing in panel set

### ISSUE THREAD

**Issue by nithinmkp** [gadenbuie/xaringanExtra#105]
![16179015397503761992023432426137](https://user-images.githubusercontent.com/65053643/114067781-d03e1280-98ba-11eb-9f64-27d24282c735.jpg)

How to remove the bullets?

**Comment by nithinmkp** [comment]
`css
ul {
  list-style-type: none;
}

ul li:before {
    content: "\f105";
    font-family: FontAwesome;
    color: red; /* or whatever color you prefer */
    margin-right: 4px;
}

`

This is the styling i am using.

**Comment by gadenbuie** [comment]
Instead of using `li::before`, you should instead style the [list marker](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker). I'm pretty sure that if you use that approach for your custom list style, it won't affect the panelset tabs.

**Comment by nithinmkp** [comment]
I tried that. But then my bullets and fonts are same colour which I don't want.
