### ISSUE TITLE
Feature Request: Keyboard Shortcut for Selecting Colors When Using Scribble

### ISSUE THREAD

**Issue by kim-soo-hwan** [gadenbuie/xaringanExtra#112]
Hi Garrick,

Thanks for your great work.
When I give a presentation on Zoom, I prefer using scribble than zoom annotation because of the shortcut, 's'.
But, whenever I change colors, I wish I could use shortcuts like below.

- 'r' for red, 'g' for green, 'b' for blue
- 'm' for magenta, 'y' for yellow, 'c' for cyan
- 'e' for eraser, 'd' for drawing
- 'n' for clean (new)

Thanks again and keep up the great work.

Cheers,
Soohwan

**Comment by gadenbuie** [comment]
I like this idea, but instead of assigning the colors to letters, I'd like to allow the user to declare a palette of 10 colors that can be quickly accessed by pressing the number keys 0-9.

**Comment by kim-soo-hwan** [comment]
That's awesome! :-)
