### ISSUE TITLE
Make gifs start when slide loaded

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#12]
or stop/start gif with click

**Comment by sharlagelfand** [comment]
YES #featurerequest

**Comment by mattwarkentin** [comment]
Would the envisioned solution for this also apply to animated SVGs? Such as those produced by `asciicast::write_svg()`. I love embedding those fake live-coding animations into a slide-deck, but of course they all start playing when the presentation loads.
