### ISSUE TITLE
xaringan_to_pdf() integration

### ISSUE THREAD

**Issue by issactoast** [gadenbuie/xaringanExtra#129]
Hello @gadenbuie

Thank you for the xaringanExtra package! I am extensively using this package especially panelset and tileview! 👍 

I run into your code for printing out the xaringan to pdf and it works perfectly on my system.

https://www.garrickadenbuie.com/blog/print-xaringan-chromote/#the-code

```r
source("https://git.io/xaringan2pdf")
```

do you have any plan to put this function in xaringanExtra?

**Comment by gadenbuie** [comment]
Thanks for the kind words, I'm glad you're enjoying xaringanExtra! And good news, a version of the function from that blog post was added to the package [xaringanBuilder](https://github.com/jhelvy/xaringanBuilder)!

**Comment by issactoast** [comment]
Wow! Thank you for all of this hard work!
