### ISSUE TITLE
Tile view and fit screen don't seem to play nicely together

### ISSUE THREAD

**Issue by mattwarkentin** [gadenbuie/xaringanExtra#14]
Hi @gadenbuie,

It seems like when you invoke the "fit screen" functionality with `Alt/Option-F` that it breaks the ability to be able to use tile view. Not sure if this is even fixable or not. Just an observation. For context, I only tested this on Chrome.

**Comment by gadenbuie** [comment]
Thanks for letting me know. In general I need to do more testing around combining extensions, but I’m not surprised these two don’t work together. Fit screen is a total hack (unlike the others) and basically breaks some core remark pieces and there’s no way to unbork it other than reloading the slides.

**Comment by mattwarkentin** [comment]
No problem! Definitely not a deal breaker.

This package is amazing, btw. The added functionality this package gives `xaringan` is so valuable. I love it.
