### ISSUE TITLE
Line indicating Panelset end?

### ISSUE THREAD

**Issue by SchmidtPaul** [gadenbuie/xaringanExtra#150]
I am creating a [distill](https://rstudio.github.io/distill/) github page and I think I want to use multiple [panelsets](https://pkg.garrickadenbuie.com/xaringanExtra/#/panelset) per article. (I guess I could also make it work via `{.tabset .tabset-fade .tabset-pills}` but the panelsets seem nicer)

However, when having text in each panel and more text after the panelset, it is not obvious where the tab-specific text ends and the general text starts:

![image](https://user-images.githubusercontent.com/31928213/148642603-6dc9b391-56bd-4bf0-97fe-71533370fba3.png)

I feel that having the same grey line that is at the top of the panelset also at the bottom of the panelset would be a big improvment. Is is possible to add this line?

Thanks!

Here's the code:

`````` r
---
title: "Test"
site: distill::distill_website
---

```{r panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

::::: {.panelset}

::: {.panel}
[Tab A]{.panel-name}

This text belongs to Tab A.
:::

::: {.panel}
[Tab B]{.panel-name}

This text belongs to Tab B.
:::

:::::

This text does not belong to either Tab A or B.
``````

**Comment by gadenbuie** [comment]
If you want a border just along the bottom of the panel, you could try adding this css to your document:

```css
.panel {
  border-bottom: 2px solid var(--panel-tabs-border-bottom);
}
```

The first place to start would be to put that in a `css` chunk in your Rmd:

````markdown
```{css echo=FALSE}
.panel {
  border-bottom: 2px solid var(--panel-tabs-border-bottom);
}
```
````

**Comment by SchmidtPaul** [comment]
Thanks a lot! I added it to my `theme.css` and it works. 
Unless you have an immediate idea how to make this even more visually intuitive, I am going to stick with this solution.
Cheers

![image](https://user-images.githubusercontent.com/31928213/148646433-5c993c5e-614c-4361-91ae-7d2642d66462.png)
