### ISSUE TITLE
share again option from xaringanExtra not showing share options upon running inifinte moon reader

### ISSUE THREAD

**Issue by koliajaykr** [gadenbuie/xaringanExtra#154]
`xaringanExtra::use_share_again()` function is not showing sharing option tab while using the infinite moon reader but working good upon knitting the slides.

**Comment by mattwarkentin** [comment]
@koliajaykr This change is by design based on the following commit: https://github.com/gadenbuie/xaringanExtra/commit/330a41537dd3fbb027b9aa8199b7b66ee7c7c0db

**Comment by koliajaykr** [comment]
Thank you @mattwarkentin for your comment.
