### ISSUE TITLE
can‘t install

### ISSUE THREAD

**Issue by pomang-211** [gadenbuie/xaringanExtra#155]
> devtools::install_github("gadenbuie/xaringanExtra")

Downloading GitHub repo gadenbuie/xaringanExtra@HEAD
√  checking for file 'C:\Users\wangbin\AppData\Local\Temp\RtmpSQTa29\remotes7a0c1f70256a\gadenbuie-xaringanExtra-ee5092d/DESCRIPTION' ... 
-  preparing 'xaringanExtra': (481ms)
√  checking DESCRIPTION meta-information ... 
   Warning in parse(con, encoding = "UTF-8") :
     argument encoding="UTF-8" is ignored in MBCS locales
   Error in parse(con, encoding = "UTF-8") : 
     invalid multibyte character in parser at line 51
   Execution halted

Error: Failed to install 'xaringanExtra' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed

**Comment by gadenbuie** [comment]
Can you please share the output of

```r
devtools::session_info()
```
