### ISSUE TITLE
Feature request: Synchronized panelsets

### ISSUE THREAD

**Issue by mvanrongen** [gadenbuie/xaringanExtra#175]
It would be helpful if the default [panel-name] could be altered at the page or website level. For example, it would be great if one could create a dropdown box to set the default [panel-name], allowing users to change language-specific code for example.

**Comment by mvanrongen** [comment]
Thanks! That sounds like a good approach to me. I was wondering if this has any effect on the compatibility in R Markdown? I use the fenced divs and I don't know if this method translates to that?

**Comment by gadenbuie** [comment]
* Completed in #195
