### ISSUE TITLE
Content of panels not displayed when using .panelset in bookdown 

### ISSUE THREAD

**Issue by Dr-Junior** [gadenbuie/xaringanExtra#183]
Hi, 

I'm trying to use panelset in bookdown. I have followed the instructions given here: https://pkg.garrickadenbuie.com/xaringanExtra/panelset//rmarkdown.html

To give an example, I'll use the Minimal book example from bookdown: 

![image](https://user-images.githubusercontent.com/113840739/190909470-c4ca8667-e791-4023-9ebc-edc86821b2da.png)

When I build the book, I get tabs for the panels but they do not contain any text (please see image below). I have tried including images and/or results from code chunks, nothing is displayed. I have also tried using Non-standard Rmd. I have tried browsers Chrome and Edge. 

![image](https://user-images.githubusercontent.com/113840739/190910502-c670585b-3256-4818-a4cc-e44ff95aad4c.png)

I have updated R, R studio and all packages. 

![image](https://user-images.githubusercontent.com/113840739/190910711-faff1a6a-3ad8-4063-858c-09ebd18c0e0e.png)
![image](https://user-images.githubusercontent.com/113840739/190910734-5c065be8-61fe-4b9e-9267-045b4400046e.png)

I hope this can be resolved, thank you for a great package!

**Comment by gadenbuie** [comment]
Hi! Sorry you've run into issues with panelset! Can you provide a minimal example, either in a repo or  by copy-pasting the contents of that Rmd into this issue?

**Comment by Dr-Junior** [comment]
Thanks for the reply, yeah sure, sorry I didn't include it in the original post. 

The repo is here: https://github.com/Dr-Junior/panelset_problem.git

When I knit or build the "index.rmd" I get the results described above. 

Of note, everything works as it should with .panelset when a start a regular R project (_i.e._ not a bookdown project) and copy/paste the code of "index.rmd" (without the YAML header) to an .rmd file and knit it. So the error seems to be related to bookdown.

**Comment by gilesnknight** [comment]
@Dr-Junior I've hit this problem before and it's to do with bookdown's CSS. Try adding this to your book's style.css:
```
.panelset .panel-active {
display: block !important;
}
```

**Comment by Dr-Junior** [comment]
@gilesnknight That worked!! My eternal thanks!

**Comment by gadenbuie** [comment]
I reopened this to remind myself to take a look and see if there's a general solution that would work for bookdown _and_ all other Rmd output formats.

**Comment by gadenbuie** [comment]
Thank you @Dr-Junior for the report and @gilesnknight for the solution!

**Comment by Dr-Junior** [comment]
Not sure if I should start a new issue but with the solution provided by @gilesnknight now the TOC links for the subheadings that contain a panelset section don't work. When I click a subheading (that contains a panelset section) in the TOC, it takes me to the main chapter but not the subheading. I don't suppose there is a simple solution for this as well?

**Comment by katrinabrock** [comment]
Thanks @gilesknight . The workaround worked for me too.
