### ISSUE TITLE
editable content across devices when html emailed

### ISSUE THREAD

**Issue by oobd** [gadenbuie/xaringanExtra#186]
Hi, 

I have a local self contained xaringan slide pack where editable text persists when I change something and refresh browser. But when I email the html file to another user, the editable text no longer functions as expected and gets reset when they reload their browser. 

Is this the expected behaviour when emailed and opened with different devices?

**Comment by gadenbuie** [comment]
Yeah, unfortunately the edits are only remembered in the browser where they were made. If you edit your slides in one browser and open them in another browser on your own computer even, your edits won't persist.

It'd be super helpful if the edits stuck around across browsers or devices, but the edits would have to stored somewhere, like a third-party server.

**Comment by oobd** [comment]
Ah, thanks for clarifying!
