### ISSUE TITLE
use_logo() doesn't handle relative URLS

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#23]
`use_logo()` doesn't work as expected with relative URLs because the CSS dependency is inside `libs/xaringanExtra-logo-xxx`.

Currently, you can work around this by adding `../../<path relative to slides>` before the path name of the logo image. But this should be handled or the CSS should be included differently.

In the following example, `use_logo("kitten.jpg")` won't work, but `use_logo("../../kitten.jpg")` will.

````markdown
---
title: "xaringanExtra use_logo issue"
output:
  xaringan::moon_reader:
    lib_dir: libs
    seal: false
---

class: center, middle

```{r include=FALSE, eval=FALSE}
# Not run inside the slide
download.file("http://placekitten.com/200/200", "kitten.jpg")
```

```{r xaringan-extra, echo=FALSE}
xaringanExtra::use_logo("kitten.jpg", width="100px")
```

# xaringan

### /ʃaː.'riŋ.ɡan/

---
class: inverse, center, middle

# Get Started

---

# Hello World

Install the **xaringan** package from [Github](https://github.com/yihui/xaringan):

```{r eval=FALSE, tidy=FALSE}
devtools::install_github("yihui/xaringan")
```
````

**Comment by gadenbuie** [comment]
Reported on [RStudio Community by Sinval](https://community.rstudio.com/t/how-can-i-add-my-logo-to-the-slides-header-lines-using-xaringan/60316)

**Comment by gadenbuie** [comment]
Okay I've fixed this, but I discovered a bug in xaringan that will break this again. Leaving open until I resolve the upstream bug.

**Comment by gadenbuie** [comment]
Never mind, this fix should work for current versions of xaringan.

**Comment by gbganalyst** [comment]
It is still not working.

**Comment by gbganalyst** [comment]
It works perfectly. Thank you @gadenbuie for this magic.
