### ISSUE TITLE
Modifying the the share bar with style_share_again doesn't seem to work

### ISSUE THREAD

**Issue by mattwarkentin** [gadenbuie/xaringanExtra#48]
Hi @gadenbuie,

I am unable to get any of the style options in `xaringanExtra::style_share_again()` to work. When I change the colour for `background` or `foreground` they remain the default colours, and any changes to `share_buttons` doesn't seem to have any affect.

````r
---
title: "Test Share Again"
author: "Matt"
output:
  xaringan::moon_reader:
    lib_dir: libs
---

```{r setup, include=FALSE}
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(
  share_buttons = "none", 
  foreground = "rgba(255, 0, 0, 0.5)",
  background = "rgb(255, 0, 0)"
  )
```

This is a test slide
````

![Screen Shot 2020-09-02 at 3 46 44 PM](https://user-images.githubusercontent.com/27825069/92029445-8644eb00-ed33-11ea-8d48-d1bd7f4304b9.png)

Also, I think there may be a spelling error in the default argument [here](https://github.com/gadenbuie/xaringanExtra/blob/f85b70a139b4001b1e36428cbf0c947e39c7d1e9/R/share_again.R#L43).

Side note: I think `use_share_again()` breaks when no author is specified in the YAML front-matter.
````r
---
title: "Test Share Again"
output:
  xaringan::moon_reader:
    lib_dir: libs
---

```{r setup, include=FALSE}
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(
  share_buttons = "none", 
  foreground = "orange",
  background = "blue"
  )
```

This is a test slide
````

**Comment by gadenbuie** [comment]
I think I squashed all those bugs, thanks for reporting them!

FYI, the reason for the original issue is `include = FALSE`. For `style_share_again()` to work in that chunk, it needs to be included, so I recommend using `echo = FALSE` instead.

**Comment by mattwarkentin** [comment]
Wowza, that has to be a world-record time for a bug fix. I installed the new dev version and can confirm all the bugs seem to be fixed.

Side compliment: The __Build your own universe__ presentation you and @tgerke built is a work of art. It took me several times through to uncover some of the easter eggs.

**Comment by mattwarkentin** [comment]
That's great! I look forward to reading more about.

After seeing your slidecraft, I began a deep-dive into learning CSS animations the last several days and I look forward to using them to enhance future presentations. 

I'm definitely interested in learning more about leader lines. I looked into that a bit, but it seems like it requires some more JS finesse than I'm generally comfortable with.

**Comment by mattwarkentin** [comment]
On topic, it seems like when the web page that contains the embedded `xaringan` presentation is loaded that the share bar _"rises"_ but doesn't ever disappear, at least thats my experience so far. I suppose the whole point is for the share bar to be present and obvious, but I'm wondering whether it would be worthwhile/possible to configure how long the share bar remains visible for after the first time the presentation is hovered/focused/clicked and then no longer hovered again?

**Comment by mattwarkentin** [comment]
Ohhh, excellent. I look forward to Leader Lines joining the team.

Yikes, I don't know how in all of my testing I never let my cursor rest on the slides for two seconds, but here we are!
