### ISSUE TITLE
Cant click on .panel_set[] tabs 

### ISSUE THREAD

**Issue by TuQmano** [gadenbuie/xaringanExtra#57]
Hi, 

1. First of all, thanks for the quick fix yesterday in #54 !

2. I am trying to build .panelset[] workflow and having problems with it. I started from examples structure and it shows in slides as it is fine. But can't get to render tab content but 1st one. This is how it looks, and an HTML inspect elements. It seems to me that I have  something wrong with the _onclick_.

In this case, I cant get de *Explorar* tab content. Only displaying the default(?) *Visualizar* one: 

![image](https://user-images.githubusercontent.com/12114624/92310043-ec727d80-ef80-11ea-9700-f449638fb3a8.png)

This is my session info: 

``` 
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Spanish_Argentina.1252      
 ctype    Spanish_Argentina.1252      
 tz       America/Buenos_Aires        
 date     2020-09-05         
...
xaringan         0.16    2020-03-31 [1] CRAN (R 4.0.2)                          
xaringanExtra    0.2.3   2020-09-04 [1] Github (gadenbuie/xaringanExtra@6271d3f)
xaringanthemer * 0.3.0   2020-05-04 [1] CRAN (R 4.0.2) 
```

Thanks for this great pkg!!!

**Comment by gadenbuie** [comment]
Hmmm, at first glance this looks okay, that onclick is expected. Can you share the source code for that slide?

**Comment by TuQmano** [comment]
Of course!

**YAML**

```
---

output:
  xaringan::moon_reader:
    seal: false
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      countdown: 60000
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
layout:true

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(collapse = TRUE,
                      fig.retina = 3,
                      ccache = TRUE,
                      warning = FALSE,
                      message = FALSE)

xaringanExtra::use_xaringan_extra(include = c("panelset", "tile_view", "webcam"))
xaringanExtra::use_logo("https://raw.githubusercontent.com/electorArg/polAr/master/hex/hex-polAr.png", width = "100px")
```

**Slide CODE**

```

#### Juan Pablo Ruiz Nicolini | **@TuQmano**

### Análisis de Datos Políicos de Argentina




### DISCURSOS

.panelset[
.panel[.panel-name[Visualizar]

.pull-left[


library(polAr)

get_speech(year = 1946) %>% 
plot_speech()


]

.pull-right[

``{r word_cloud, echo=F}
knitr::include_graphics(path = "polar_slides_files/img-manual/peron_1946.png")
``
]]

.panel[.panel-name[Explorar]


``{r}
polAr::show_available_speech()
``

]

]

```

**Comment by TuQmano** [comment]
I think that my problem is in how the tabs links/urls are build. If I right-click with the mouse and copy it, it´s structure is similar to the documentation example, but it doesn´t redirect to the expected content. 

`file:///C:/Users/Documents/latinr2020/slides/polAr/polar_slides.html?panelset=explorar#panelset_explorar`

**Comment by gadenbuie** [comment]
Turns out the real culprit was the logo. I made a small change and now ` use_logo()` should play nicely with other extensions. Let me know if it gives you any trouble!

**Comment by TuQmano** [comment]
working nicely, thanks!
