### ISSUE TITLE
xaringanExtra::use_panelset() PDF

### ISSUE THREAD

**Issue by RRMaximiliano** [gadenbuie/xaringanExtra#74]
Is there a way to export the slides to PDF and keep the panelsets in different pages (i.e., 1 panel per page)? I have tried using `pagedown::chrome_print()` but when I export it I get only the first panel to show.

**Comment by mattwarkentin** [comment]
Hi @RRMaximiliano,

I believe this is a duplicate issue of #45 and #46. I don't think has been solved yet, but it looks like Garrick is thinking through the best approach to add this feature.

**Comment by gadenbuie** [comment]
For long-term support in this package see #45. For an immediate solution, I've posted a function to print slides with panelsets here: https://www.garrickadenbuie.com/blog/print-xaringan-chromote/
