### ISSUE TITLE
Equivalent revealjs package

### ISSUE THREAD

**Issue by py9mrg** [gadenbuie/xaringanExtra#77]
Hello,

This is not an issue more an extreme feature request! I absolutely love xaringanExtra and is the main reason I use xaringan - particularly how it allows such simple marrying of colour/font themes and ggplot graphics.

However, I have found some really weird font size scaling issues with xaringan (actually with remark.js) that don't happen with [revealjs](https://cran.r-project.org/web/packages/revealjs/index.html) (which, obviously, uses reveal.js). I was wondering how much of a nightmare it would be to make an equivalent revealjsExtra package? I am naively hoping that, because a lot of this is CSS/html styling, it might not be as much work as it seems at first sight so you could change a few lines here and bish bash bosh?

**Comment by gadenbuie** [comment]
The good news is that many things in this package are actually R Markdown extensions that happen to be helpful for xaringan slides. So you can try to use any of the extensions here for revealjs. The bad news is that if it's something that I've designed specifically for xaringan, then it very likely _isn't_ something that could easily be ported to revealjs.

**Comment by py9mrg** [comment]
Aaaaaah ok. Thanks for the info and consideration. And thanks for the package! I may just stick with xaringan then and accept having to do a bit of manual font scaling adjustment.
