### ISSUE TITLE
Feature Request: Slide Search

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#82]
For slides that are let available after a talk, or for slides shared during tutorials, that would be great if attendees could be able to search the content.
There exists this feature that has not been updated for a while for {remark.js}, this can be a good start: https://github.com/arestivo/remark.search

__Originally posted by @statnmap in https://github.com/yihui/xaringan/issues/295__

**Comment by statnmap** [comment]
This works perfectly ! Thank you so much !

It does work play nice along with tileview mode though, as when you press "o" in the search bar, it switches to the overview mode. But alone, it works exactly as expected.

**Comment by gadenbuie** [comment]
Yikes, thanks for letting me know @statnmap .. I'll have a fix soon
