### ISSUE TITLE
infinite moon reader not working with `use_tile_view()`

### ISSUE THREAD

**Issue by youngwoos** [gadenbuie/xaringanExtra#91]
Rendering fails when running infine moon reader with `use_tile_view()` used.
I ran it on docker image: rocker verse 4.0.4.

If `use_tile_view()` is in the code chunk and I modify the script and run the infine moon reader, the html is generated but RStudio preview does not work.

**Comment by gadenbuie** [comment]
Hi! I just tested tile view in the latest `rocker/verse` container with R 4.0.4 and the latest `xaringan` and `xaringanExtra` packages. I didn't notice anything unusual.

There are a few things that could help me track down the issue, if it's something that you can reproduce reliably:

1. The output from `sessioninfo::package_info(c("xaringan", "xaringanExtra"))`
2. The document you are using that causes the issue (or as little as possible of the slides `.Rmd` file that still produces the problem)
3. Some screenshots or screen recordings of what you see when the problem happens.

**Comment by youngwoos** [comment]
Thank you for answering.

I couldn't reproduce now. I'm not sure what's wrong but I guess `infinite_moon_reader()` makes a problem when rmd script is long.
If the problem occurs again and I will ask you.
