### ISSUE TITLE
use_logo breaks the slide

### ISSUE THREAD

**Issue by dmi3kno** [gadenbuie/xaringanExtra#93]
I am starting a new {xaringanthemer} presentation from the template and inserting the recommended chunk just on the first slide

```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "https://raw.githubusercontent.com/rstudio/hex-stickers/master/PNG/xaringan.png"
)
```
I am getting this
![Screenshot from 2021-02-27 12-23-17](https://user-images.githubusercontent.com/13419011/109385781-aa564300-78f6-11eb-80a9-0e2f3affda91.png)

Do you have an idea what could be going wrong with my setup. It is not the first time I am seeing problems with use_logo, but first time that it fails this evidently (in the past logo would just disappear from the slides).

**Comment by gadenbuie** [comment]
Does the solution in https://github.com/gadenbuie/xaringanExtra/issues/78 work for you?

**Comment by dmi3kno** [comment]
It does. Sorry about not checking closed issues. Could, perhaps, a caveat be added to the documentation (the README)?
