### ISSUE TITLE
[scribble] Minor improvements

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanExtra#95]
- [x] Mouse in and then out of the toolbox can sometimes trigger drawing mode when the timeout is reached. It should instead hide the toolbox.
- [x] The eraser cursor should update position immediately when shown, or we should only show the cursor when its inside the slide box
- [x] Have we correctly handled drawing inside the toolbox when the tools are inside the slide?

**Comment by mattwarkentin** [comment]
> The eraser cursor should update position immediately when shown, or we should only show the cursor when its inside the slide box

I had good intentions to use the current mouse position to immediately update the eraser cursor location (instead of waiting for mouse movement) but I forgot. Whoops.

> Have we correctly handled drawing inside the toolbox when the tools are inside the slide?

I think this works fine and the lines will be drawn underneath the toolbox, as the toolbox sits on top of the canvas layers.

**Comment by mattwarkentin** [comment]
I don't know where else to put this so: Through the process of collaborating on `scribble`, I learned a lot about `remark.js`, `xaringan`, `xaringanExtra`, and HTML/CSS/JavaScript, and I'd love to keep developing these skills. If there's ever a new feature/extension that you don't have the time/motivation to implement yourself, or you just think it would be something cool for me to work on, I would definitely be interested in contributing again. I just wanted to throw that out there and leave it with you.

Great presentation for the New York OSP Meetup, btw!

**Comment by mattwarkentin** [comment]
Bug report: See https://github.com/gadenbuie/xaringanExtra/pull/87#issuecomment-797022330

**Comment by gadenbuie** [comment]
> I don't know where else to put this so: Through the process of collaborating on `scribble`, I learned a lot about `remark.js`, `xaringan`, `xaringanExtra`, and HTML/CSS/JavaScript, and I'd love to keep developing these skills. If there's ever a new feature/extension that you don't have the time/motivation to implement yourself, or you just think it would be something cool for me to work on, I would definitely be interested in contributing again. I just wanted to throw that out there and leave it with you.

Thanks Matt! That's great to hear — I think making cool things for xaringan is a great way to learn web dev, _and_ you made an awesome new feature. It's really cool to see people using it already! 😃 

If you have any ideas about new features or other fun things, feel free to run with it and contribute. I'm all for it!
